---
apiVersion: v1
kind: Service
metadata:
  name: plex 
  labels:
    app.kubernetes.io/name: plex 
spec:
  ports:
    - port: 32400 
      targetPort: 32400 
      protocol: TCP
      name: http
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: plex 

---
apiVersion: v1
kind: Pod 
metadata:
  name: plex
  labels:
    app.kubernetes.io/name: plex 
spec:
  hostname: bender
  containers:
    - name: plex 
      image: plexinc/pms-docker 
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          gpu.intel.com/i915: 1
      env:
        - name: VERSION 
          value: docker 
        - name: PGID 
          value: "1000" 
        - name: PUID 
          value: "1000" 
        - name: TZ 
          value: America/Chicago 
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: secrets 
              key: PLEX_CLAIM
      ports:
        - name: http
          containerPort: 32400 
          protocol: TCP
      volumeMounts:
        - name: data
          mountPath: /data/
        - name: config 
          mountPath: /config/
  volumes:
    - name: data
      hostPath:
        path: /storage/k3s/plex/data
        type: DirectoryOrCreate
    - name: config 
      hostPath:
        path: /storage/k3s/plex/config
        type: DirectoryOrCreate
