---
apiVersion: v1
kind: Service
metadata:
  name: plex 
  labels:
    app.kubernetes.io/name: plex 
spec:
  ports:
    - port: 32400 
      targetPort: 32400 
      protocol: TCP
      name: http
    - port: 3005 
      targetPort: 3005 
      protocol: TCP
      name: plex-companion 
    - port: 5353 
      targetPort: 5353 
      protocol: UDP 
      name: discovery 
    - port: 8342 
      targetPort: 8342 
      protocol: TCP 
      name: roku 
  selector:
    app.kubernetes.io/name: plex 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app.kubernetes.io/name: plex 
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: plex 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex 
    spec:
      containers:
        - name: plex 
          image: linuxserver/plex 
          env:
            - name: VERSION 
              value: docker 
            - name: PGID 
              value: "1000" 
            - name: PUID 
              value: "1000" 
            - name: TZ 
              value: America/Chicago 
            - name: PLEX_CLAIM_BROKEN
              valueFrom:
                secretKeyRef:
                  name: secrets 
                  key: PLEX_CLAIM 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 32400 
              protocol: TCP
            - name: plex-companion 
              containerPort: 3005
              protocol: TCP 
            - name: discovery 
              containerPort: 5353 
              protocol: UDP 
            - name: roku 
              containerPort: 8324
              protocol: TCP 
          volumeMounts:
            - name: data
              mountPath: /data/
            - name: config 
              mountPath: /config/
      volumes:
        - name: data
          hostPath:
           path: /storage/k3s/plex/data
           type: DirectoryOrCreate
        - name: config 
          hostPath:
           path: /storage/k3s/plex/config
           type: DirectoryOrCreate

